name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 8,20 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Bims-sh/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Bims-sh
          commits_authoring: Bims, DasIschBims, Bims-sh
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_user: Bims
          plugin_wakatime_sections: time, languages, os, editors, languages-graphs, editors-graphs
          plugin_wakatime_days: 180
          plugin_wakatime_limit: 5
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount
